import pandas as pd
import numpy as np
import ta
import sqlite3
from src.data.storage import DataStore

class FeatureEngineer:
    def __init__(self, db_path="data/market_data.db"):
        self.db = DataStore(db_path)
    
    def load_price_data(self, symbol):
        """Loads stock prices from DB."""
        conn = self.db.get_connection()
        query = f"SELECT * FROM stock_prices WHERE symbol='{symbol}' ORDER BY timestamp"
        try:
            df = pd.read_sql(query, conn)
            df['timestamp'] = pd.to_datetime(df['timestamp'])
            df.set_index('timestamp', inplace=True)
            # Ensure proper float types
            for col in ['open', 'high', 'low', 'close']:
                df[col] = df[col].astype(float)
            return df
        except Exception as e:
            print(f"Error loading price data for {symbol}: {e}")
            return pd.DataFrame()
        finally:
            conn.close()

    def load_news_sentiment(self, symbol):
        """Loads and aggregates daily sentiment."""
        conn = self.db.get_connection()
        query = f"SELECT * FROM news WHERE symbol='{symbol}'"
        try:
            df = pd.read_sql(query, conn)
            if df.empty:
                return pd.DataFrame(columns=['sentiment_score'])
            
            df['published'] = pd.to_datetime(df['published'], errors='coerce')
            df['date'] = df['published'].dt.date
            
            # Aggregate by date
            daily_sentiment = df.groupby('date')['sentiment_score'].mean()
            return daily_sentiment.to_frame()
        except Exception as e:
            print(f"Error loading news for {symbol}: {e}")
            return pd.DataFrame()
        finally:
            conn.close()
            
    def load_fundamentals(self, symbol):
        """Loads latest fundamentals."""
        conn = self.db.get_connection()
        query = f"SELECT * FROM fundamentals WHERE symbol='{symbol}'"
        try:
            df = pd.read_sql(query, conn)
            # We will just pivot this to get a single row or replicate it
            # For simplicity, we take the latest value for each metric
            if df.empty:
                return pd.Series()
            
            # Since we only have one snapshot usually in this demo, just take latest
            latest = df.sort_values('fetched_at').drop_duplicates('metric', keep='last')
            return latest.set_index('metric')['value']
        except Exception as e:
            print(f"Error loading fundamentals for {symbol}: {e}")
            return pd.Series()
        finally:
            conn.close()

    def add_technical_indicators(self, df):
        """Adds RSI, MACD, SMA to the price dataframe."""
        if df.empty: return df
        
        # simple moving averages
        # Use smaller windows for testing if data is small
        if len(df) < 50:
            df['SMA_10'] = ta.trend.sma_indicator(df['close'], window=5)
            df['SMA_20'] = ta.trend.sma_indicator(df['close'], window=10)
        else:
            df['SMA_10'] = ta.trend.sma_indicator(df['close'], window=10)
            df['SMA_20'] = ta.trend.sma_indicator(df['close'], window=20)
        
        # RSI
        # 14 is standard, but if we have less, use smaller
        rsi_window = 14 if len(df) > 20 else 5
        df['RSI'] = ta.momentum.rsi(df['close'], window=rsi_window)
        
        # MACD
        # Standard: 12, 26, 9
        if len(df) > 30:
            macd = ta.trend.MACD(df['close'])
        else:
            # Fast, Slow, Signal
            macd = ta.trend.MACD(df['close'], window_fast=3, window_slow=6, window_sign=3)
            
        df['MACD'] = macd.macd()
        df['MACD_signal'] = macd.macd_signal()
        
        # Volatility (Bollinger Bands width)
        bb_window = 20 if len(df) > 25 else 5
        bb = ta.volatility.BollingerBands(df['close'], window=bb_window)
        df['BB_width'] = bb.bollinger_wband()
        
        return df

    def create_target(self, df, window=1, threshold=0.01):
        """
        Creates target variable:
        1 (BUY): Return > threshold
        -1 (SELL): Return < -threshold
        0 (HOLD): Otherwise
        """
        # Calculate future return 'window' steps ahead
        # We need to shift backward to compare current price with future price
        # Return = (Price_t+n - Price_t) / Price_t
        df['future_close'] = df['close'].shift(-window)
        df['future_return'] = (df['future_close'] - df['close']) / df['close']
        
        conditions = [
            (df['future_return'] > threshold),
            (df['future_return'] < -threshold)
        ]
        choices = [1, -1]
        
        df['target'] = np.select(conditions, choices, default=0)
        
        # Drop NaN generated by shift (last 'window' rows)
        df.dropna(subset=['future_return'], inplace=True)
        return df

    def prepare_data(self, symbol, is_training=True, live_price=None):
        """Orchestrates the data prep for a symbol."""
        # 1. Price + Technicals
        price_df = self.load_price_data(symbol)
        if price_df.empty: 
            print("Price data empty")
            return None
            
        # --- Live Price Injection ---
        if live_price is not None and len(price_df) > 0:
            try:
                live_price = float(live_price)
                last_ts = price_df.index[-1]
                now = pd.Timestamp.now()
                
                # Check if last candle is today (naive check, timezone might differ but good enough for demo)
                if last_ts.date() == now.date():
                    # Update existing candle
                    price_df.at[last_ts, 'close'] = live_price
                    # Update High/Low if breached
                    if live_price > price_df.at[last_ts, 'high']: price_df.at[last_ts, 'high'] = live_price
                    if live_price < price_df.at[last_ts, 'low']: price_df.at[last_ts, 'low'] = live_price
                else:
                    # Append new candle for today
                    new_row = pd.Series({
                        'open': live_price, 
                        'high': live_price, 
                        'low': live_price, 
                        'close': live_price, 
                        'volume': 0
                    }, name=now)
                    # FIX: Create DataFrame with correct index name if needed, but T is easiest
                    new_df = new_row.to_frame().T
                    price_df = pd.concat([price_df, new_df])
                
                # print(f"Injected live price {live_price} for {symbol}")
            except Exception as e:
                print(f"Live injection error: {e}")

        # print(f"Loaded {len(price_df)} price rows")

        # print(f"Loaded {len(price_df)} price rows")
        
        price_df = self.add_technical_indicators(price_df)
        # print(f"After technicals: {len(price_df)} rows")
        
        # 2. Sentiment
        sentiment_df = self.load_news_sentiment(symbol)
        # Merge sentiment on date
        price_df['date'] = price_df.index.date
        
        # Left join to keep price rows (fills missing sentiment with 0 or fillna)
        merged = price_df.reset_index().merge(sentiment_df, on='date', how='left')
        merged.set_index('timestamp', inplace=True) 
        # Forward fill sentiment (sentiment persists until new news)
        merged['sentiment_score'] = merged['sentiment_score'].ffill()
        merged['sentiment_score'].fillna(0, inplace=True) # Neutral if no news EVER
        
        print(f"After merge: {len(merged)} rows")
        
        # 3. Fundamentals (Broadcast to all rows)
        fund_series = self.load_fundamentals(symbol)
        for metric, value in fund_series.items():
            merged[metric] = value
            
        # Handle missing fundamentals (e.g., pegRatio might be None)
        # Fill numeric NaNs with 0 (or median in real app)
        merged.fillna(0, inplace=True)
            
        # 4. Target (Only if training)
        if is_training:
            merged = self.create_target(merged)
            print(f"After target creation: {len(merged)} rows")
            
            # Drop rows with NaN in target/return (due to shift)
            merged.dropna(subset=['target', 'future_return'], inplace=True)
        else:
            # For inference, we still might want to create columns but NOT drop
            # But the model expects X to have specific columns. 
            # If the model does NOT use 'target' or 'future_return' as features (it shouldn't), we are fine.
            # We just return the full DF so we get the latest row.
            pass
        
        print(f"Final data size: {len(merged)}")
        
        return merged

if __name__ == "__main__":
    fe = FeatureEngineer()
    # Test with one symbol
    df = fe.prepare_data("RELIANCE.NS")
    if df is not None:
        print(f"Prepared data shape: {df.shape}")
        print(df[['close', 'RSI', 'sentiment_score', 'target']].tail())
    else:
        print("Failed to prepare data.")
